local BrainrotData = {}

BrainrotData.Types = {
    -- --- COMUNES ---
    ["Common1"] = {
        Name = "Lirili Larila",
        Category = "Común",
        Mutation = "Sin mutaciones",
        BaseIncome = 1,
        BaseUpgradeCost = 10,
        RotationOffset = Vector3.new(0, 0, 0),
    },
    ["Common2"] = {
        Name = "Boneca Ambalabu",
        Category = "Común",
        Mutation = "Sin mutaciones",
        BaseIncome = 2,
        BaseUpgradeCost = 25,
        RotationOffset = Vector3.new(0, 0, 0),
    },
    ["Common3"] = {
        Name = "Brr Brr Patapim",
        Category = "Común",
        Mutation = "Sin mutaciones",
        BaseIncome = 3,
        BaseUpgradeCost = 50,
        RotationOffset = Vector3.new(0, 0, 0),
    },
    ["Common4"] = {
        Name = "Tripi Tropi",
        Category = "Común",
        Mutation = "Sin mutaciones",
        BaseIncome = 5,
        BaseUpgradeCost = 100,
        RotationOffset = Vector3.new(0, 0, 0),
    },
    ["Common5"] = {
        Name = "Svinino Biombondino",
        Category = "Común",
        Mutation = "Sin mutaciones",
        BaseIncome = 8,
        BaseUpgradeCost = 200,
        RotationOffset = Vector3.new(0, 0, 0),
    },

    -- --- COMUNES (ORO) ---
    ["CommonGold1"] = {
        Name = "Lirili Larila (Oro)",
        Category = "Común",
        Mutation = "Oro",
        BaseIncome = 2,
        BaseUpgradeCost = 20,
        RotationOffset = Vector3.new(0, 0, 0),
    },
    ["CommonGold2"] = {
        Name = "Boneca Ambalabu (Oro)",
        Category = "Común",
        Mutation = "Oro",
        BaseIncome = 4,
        BaseUpgradeCost = 50,
        RotationOffset = Vector3.new(0, 0, 0),
    },
    ["CommonGold3"] = {
        Name = "Brr Brr Patapim (Oro)",
        Category = "Común",
        Mutation = "Oro",
        BaseIncome = 6,
        BaseUpgradeCost = 100,
        RotationOffset = Vector3.new(0, 0, 0),
    },
    ["CommonGold4"] = {
        Name = "Tripi Tropi (Oro)",
        Category = "Común",
        Mutation = "Oro",
        BaseIncome = 10,
        BaseUpgradeCost = 200,
        RotationOffset = Vector3.new(0, 0, 0),
    },
    ["CommonGold5"] = {
        Name = "Svinino Biombondino (Oro)",
        Category = "Común",
        Mutation = "Oro",
        BaseIncome = 16,
        BaseUpgradeCost = 400,
        RotationOffset = Vector3.new(0, 0, 0),
    },

    -- --- POCO COMUNES ---
    ["Uncommon1"] = {
        Name = "Pipi Kiwi",
        Category = "Poco común",
        Mutation = "Sin mutaciones",
        BaseIncome = 15,
        BaseUpgradeCost = 600,
        RotationOffset = Vector3.new(0, 0, 0),
    },
    ["Uncommon2"] = {
        Name = "Ballerina Cappuccina",
        Category = "Poco común",
        Mutation = "Sin mutaciones",
        BaseIncome = 25,
        BaseUpgradeCost = 1200,
        RotationOffset = Vector3.new(0, 0, 0),
    },
    ["Uncommon3"] = {
        Name = "Chimpanzini Bananini",
        Category = "Poco común",
        Mutation = "Sin mutaciones",
        BaseIncome = 40,
        BaseUpgradeCost = 2500,
        RotationOffset = Vector3.new(0, 0, 0),
    },
    ["Uncommon4"] = {
        Name = "Tung Sahur",
        Category = "Poco común",
        Mutation = "Sin mutaciones",
        BaseIncome = 65,
        BaseUpgradeCost = 5000,
        RotationOffset = Vector3.new(0, 0, 0),
    },
    ["Uncommon5"] = {
        Name = "Cappuccino Assassino",
        Category = "Poco común",
        Mutation = "Sin mutaciones",
        BaseIncome = 100,
        BaseUpgradeCost = 10000,
        RotationOffset = Vector3.new(0, 0, 0),
    },

    -- --- RAROS ---
    ["Rare1"] = {
        Name = "Ta Ta Ta Ta Sahur",
        Category = "Raro",
        Mutation = "Sin mutaciones",
        BaseIncome = 200,
        BaseUpgradeCost = 25000,
        RotationOffset = Vector3.new(0, 0, 0),
    },
    ["Rare2"] = {
        Name = "Frigo Camelo",
        Category = "Raro",
        Mutation = "Sin mutaciones",
        BaseIncome = 350,
        BaseUpgradeCost = 50000,
        RotationOffset = Vector3.new(0, 0, 0),
    },
    ["Rare3"] = {
        Name = "Trulimero Trulicina",
        Category = "Raro",
        Mutation = "Sin mutaciones",
        BaseIncome = 600,
        BaseUpgradeCost = 100000,
        RotationOffset = Vector3.new(0, 0, 0),
    },
    ["Rare4"] = {
        Name = "Pipi Potato",
        Category = "Raro",
        Mutation = "Sin mutaciones",
        BaseIncome = 1000,
        BaseUpgradeCost = 200000,
        RotationOffset = Vector3.new(0, 0, 0),
    },
    ["Rare5"] = {
        Name = "Cavallo Virtuoso",
        Category = "Raro",
        Mutation = "Sin mutaciones",
        BaseIncome = 1800,
        BaseUpgradeCost = 450000,
        RotationOffset = Vector3.new(0, 0, 0),
    },

    -- --- LEGENDARIOS ---
    ["Legendary1"] = {
        Name = "The Final Boss",
        Category = "Legendario",
        Mutation = "Sin mutaciones",
        BaseIncome = 3500,
        BaseUpgradeCost = 1000000,
        RotationOffset = Vector3.new(0, 0, 0),
    },
    ["Legendary2"] = {
        Name = "Maximum Brainrot",
        Category = "Legendario",
        Mutation = "Sin mutaciones",
        BaseIncome = 6000,
        BaseUpgradeCost = 2200000,
        RotationOffset = Vector3.new(0, 0, 0),
    },
    ["Legendary3"] = {
        Name = "Alpha Sigma",
        Category = "Legendario",
        Mutation = "Sin mutaciones",
        BaseIncome = 10000,
        BaseUpgradeCost = 5000000,
        RotationOffset = Vector3.new(0, 0, 0),
    },
    ["Legendary4"] = {
        Name = "Skibidi God",
        Category = "Legendario",
        Mutation = "Sin mutaciones",
        BaseIncome = 18000,
        BaseUpgradeCost = 12000000,
        RotationOffset = Vector3.new(0, 0, 0),
    },
    ["Legendary5"] = {
        Name = "Universal Brainrot",
        Category = "Legendario",
        Mutation = "Sin mutaciones",
        BaseIncome = 35000,
        BaseUpgradeCost = 30000000,
        RotationOffset = Vector3.new(0, 0, 0),
    },

    -- --- SECRETOS ---
    ["Secret1"] = {
        Name = "Las combinaciones",
        Category = "Secreto",
        Mutation = "Sin mutaciones",
        BaseIncome = 100000,
        BaseUpgradeCost = 150000000,
        RotationOffset = Vector3.new(0, 0, 0),
    },
    ["Secret2"] = {
        Name = "OVNI",
        Category = "Secreto",
        Mutation = "Sin mutaciones",
        BaseIncome = 500000,
        BaseUpgradeCost = 1000000000,
        RotationOffset = Vector3.new(0, 0, 0),
    }
}

return BrainrotData
